# Generated by Django 2.1.3 on 2018-11-20 23:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='UserConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('questionnarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='questionnaires.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inputs', to='questionnaires.UserConversation')),
                ('current_node', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.QuestionNode')),
            ],
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='root_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.QuestionNode'),
        ),
        migrations.AddField(
            model_name='answervariant',
            name='next_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.QuestionNode'),
        ),
        migrations.AddField(
            model_name='answervariant',
            name='parent_question',
            field=models.ForeignKey(limit_choices_to=5, on_delete=django.db.models.deletion.CASCADE, related_name='answer_variants', to='questionnaires.QuestionNode'),
        ),
    ]
